#!/usr/bin/env -S deno run -A --watch
const unit = 50;
Deno.serve({port:80}, (req:Request) => {
    const u = unit;
    return new Response(/*html*/`
        <!DOCTYPE html>
        <html>
            <head>
                <title>Coder's Arena</title>
                <style>
                    :focus {outline:none}
                    html {height:100%}
                    body {
                        display: grid;
                        height: calc(100% - ${0.2*u}px);
                        grid-template: ${0.5*u}px ${u}px auto ${0.5*u}px / auto ${0.2*u}px auto ${0.2*u}px auto;
                        margin: 0;
                        padding: ${0.1*u}px;
                    }
                    #div-l {grid-area:3/2}
                    #div-r {grid-area:3/4}
                    #div-l,#div-r {
                        background-color: #222;
                    }
                    #title {
                        grid-area:1/1/span 1/span 5;
                        text-align: center;
                    }
                    #tabs {
                        display: flex;
                        grid-area:2/1/span 1/span 5;
                    }
                    #tabs button {
                        flex-grow: 1;
                    }
                    #info {
                        grid-area:3/1;
                    }
                    #code {
                        grid-area:3/3;
                        font: ${0.3*u}px Courier;
                        border: 0;
                    }
                    #result {
                        display: grid;
                        grid-template: ${u}px auto ${u}px;
                        grid-area:3/5;
                    }
                    #time {
                        grid-area:4/1/span 1/span 5;
                        text-align: center;
                    }
                    #home, #over, #wait {
                        grid-area: 2/1/span 2/span 5;
                    }
                </style>
            </head>
            <body>
                <!-- Title -->
                <div id="title">Coder's Arena</div>
                <!-- Draggable vertical markers -->
                <div id="div-l"></div>
                <div id="div-r"></div>
                <!-- Problems -->
                <div id="tabs">
                    <button>FizzBuzz</button>
                    <button>Trailling Zeros</button>
                    <button>Digital Root</button>
                    <button>Diamond Elegance</button>
                    <button>Roman Numeral</button>
                </div>
                <!-- Problem Statement -->
                <div id="info">
                    <div>Problem Statement</div>
                </div>
                <!-- Code -->
                <textarea id="code" spellcheck="false" autocorrect="off" autocapitalize="off" autocomplete="off"></textarea>
                <!-- Running -->
                <div id="result">
                    <div id="cases">
                        <button>00</button>
                        <button>01</button>
                        <button>02</button>
                        <button>03</button>
                    </div>
                    <div id="match">
                        Enter inte<span>r</span>ger: 5<br>
                    </div>
                    <div id="action">
                        <button>Test</button>
                        <button>Submit</button>
                        <button>Finish</button>
                    </div>
                </div>
                <!-- Time limit -->
                <div id="time">
                    01:20:45 left
                </div>
                <!-- Registering -->
                <div id="home">
                    <h1>Welcome to Coder's Arena 2025!</h1>
                    <p>Enter Name:</p>
                    <input name="name"></input>
                    <p>Select Language:</p>
                    <select name="language">
                        <option>Python</option>
                        <option>Java</option>
                        <option>C++</option>
                        <option>C</option>
                    </select>
                    <button>Apply!</button>
                    <!-- If already applied -->
                    <p>Okay your registered! Wait for the competition to start</p>
                </div>
                <!-- Waiting -->
                <div id="wait">
                    <h1>You submited, wait for competition to end</h1>
                    <button>Go back</button>
                </div>
                <!-- Over -->
                <div id="over">
                    <h1>The Coder's Area is finished!</h1>
                    <p>Here are the winners!</p>
                    <h3>Python</h3>
                    <table>
                        <tr><th>Name</th><th>Points</th></tr>
                    </table>
                    <h3>Java</h3>
                    <table>
                        <tr><th>Name</th><th>Points</th></tr>
                    </table>
                    <h3>C</h3>
                    <table>
                        <tr><th>Name</th><th>Points</th></tr>
                    </table>
                    <h3>C++</h3>
                    <table>
                        <tr><th>Name</th><th>Points</th></tr>
                    </table>
                </div>
            </body>
        </html>
    `, {
        headers: {'content-type':'html'}
    });
})